### ISSUE TITLE
Why the values of achieved attack_weight are all -1 or 0

### ISSUE THREAD

**Issue by liyunqianggyn** [elliothe/Neural_Network_Weight_Attack#1]
The result that 13 bits can crush all 93 million bits, is amazing and interesting. 

In the code:

                    # change the weight to attacked weight and get loss
                    module.weight.data = attack_weight

When I print the "attack_weight", it is not full precision values, it is all -1 or 0 tensor. Is there something I miss, may I have you answer? thank you!

**Comment by elliothe** [comment]
The attack is performed on the quantized weights, as we discussed in our paper. Therefore, it should not be full precision values. For the 93million bits one, we did the 8-bit quantization encoded the weights in 2's complement format.

**Comment by liyunqianggyn** [comment]
I understood the 8-bits setting, the print attack_weight comparing with clean weights is confusing, they have same dimensions but the values are quite different.  attack_weight is similar as binary weights, below I plot them. 

attack_weight: 
tensor([[[[  -1.,   -1.,   -1.,  ...,    0.,    0.,   -1.],
          [   0.,    0.,   -1.,  ...,   -1.,   -1.,    0.],
          [  -1.,    0.,    0.,  ...,    0.,    0.,    0.],
          ...,
          [  -1.,    0.,    0.,  ...,   -1.,   -1.,   -1.],
          [   0.,    0.,    0.,  ...,    0.,    0.,    0.],
          [  -1.,   -1.,   -1.,  ...,   -1.,   -1.,   -1.]],
........]]]]]


clean_weight
tensor([[[[-1.0419e-02, -6.1356e-03, -1.8098e-03,  ...,  5.6615e-02,
            1.7083e-02, -1.2694e-02],
          [ 1.1083e-02,  9.5276e-03, -1.0993e-01,  ..., -2.7124e-01,
           -1.2907e-01,  3.7424e-03],
          [-6.9434e-03,  5.9089e-02,  2.9548e-01,  ...,  5.1972e-01,
            2.5632e-01,  6.3573e-02],
          ...,.......]]]]]

**Comment by elliothe** [comment]
I think you did not exactly follow the steps, here the clean weight should be an integer value instead of the floating-point format. You could check my other repo: https://github.com/elliothe/BFA. I think the steps to reproduce the experiments are more clear over there. Let me know if it still does not work

**Comment by liyunqianggyn** [comment]
I thought I miss something like: convert to twos complement into unsigned integer, I will go it step by step. Really a nice, motivated paper, I like it a lot, thank you very much!
