### ISSUE TITLE
Validation accuracy drop after loading checkpoints

### ISSUE THREAD

**Issue by kaiii0328** [elliothe/Neural_Network_Weight_Attack#2]
Hi I have trained a resnet18_quan on cifar10, with a top-1 validation accruacy of 69%. However, when I load the model from saved checkpoints, (before conducting BFA), the top-1 validation accuracy drops to 3%. Similar issues happens on other models. Do you have any clues for this?

**Comment by elliothe** [comment]
@kaiii0328 Have you addressed your problem? You can check another updated repository with more detailed instructions about how to reproduce the experiments: [https://github.com/elliothe/BFA](https://github.com/elliothe/BFA
)
